package latmath.util.dialog;

import java.awt.event.ActionListener;
import javax.swing.JPanel;

/**
 * Basic template for location filter configuration dialogs.
 * <p>
 * This template may be used to avoid some coding.
 *
 * @version 1.0, 2012-01-29
 * @author  Thomas Hillebrandt <t.hillebrandt@t-online.de>
 * @since   LatMath 1.0
 */
public class ConfigDialog extends javax.swing.JDialog {

    private boolean dialogResult;
    
    /** Creates new form LocationFilterConfigDialog */
    public ConfigDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(parent);
    }

    public void setContent(JPanel content) {
        pMain.add(content, java.awt.BorderLayout.CENTER);
    }

    public void setOKAction(ActionListener l) {
        bOK.addActionListener(l);
    }

    public void setCancelAction(ActionListener l) {
        bCancel.addActionListener(l);
    }

    /**
     * Make dialog visible.
     *
     * @param title The title of the dialog.
     * @param resizable If the dialog is resizable or not.
     */
    public void showDialog(String title, boolean resizable) {
        setTitle(title);
        setResizable(resizable);
        invalidate();
        pack();
        setVisible(true);
    }

    /**
     * The return value of this function can be used to reflect if
     * the settings have been changed.
     * <p>
     * Normally when pressing OK new settings are applied.
     * 
     * @return {@code true} if the OK button was pressed;
     *         {@code false} if the CANCEL button was pressed.
     */
    public boolean getDialogResult() {
        return dialogResult;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pBorder = new javax.swing.JPanel();
        pMain = new javax.swing.JPanel();
        pButtons = new javax.swing.JPanel();
        bOK = new javax.swing.JButton();
        bCancel = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        pBorder.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 1, 10));
        pBorder.setLayout(new java.awt.BorderLayout());

        pMain.setLayout(new java.awt.BorderLayout());
        pBorder.add(pMain, java.awt.BorderLayout.CENTER);

        bOK.setText("OK");
        bOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bOKActionPerformed(evt);
            }
        });
        pButtons.add(bOK);

        bCancel.setText("Cancel");
        pButtons.add(bCancel);

        pBorder.add(pButtons, java.awt.BorderLayout.SOUTH);

        getContentPane().add(pBorder, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bOKActionPerformed
        this.dialogResult = true;
    }//GEN-LAST:event_bOKActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bCancel;
    private javax.swing.JButton bOK;
    private javax.swing.JPanel pBorder;
    private javax.swing.JPanel pButtons;
    private javax.swing.JPanel pMain;
    // End of variables declaration//GEN-END:variables

}
